### ISSUE TITLE
when I run the code ,I found this problem.How can I sove this

### ISSUE THREAD

**Issue by llzz11** [Johnson-Wang/molatics#1]
__  __ ____  _____ ____
|  \/  |  _ \|  ___/ ___|
| |\/| | | | | |_ | |
| |  | | |_| |  _|| |___
|_|  |_|____/|_|   \____|

                         1.3

##########force_constants.hdf5 is read and tunned to satisfy symmetry conditions#############
Precision used for reducing symmetry constraints: 1.000000e-06
Translational invariance: ON
Rotational invariance: ON
##########Checking the invariance conditions for the given force constants#############
max drift of force constants: -2.51187959321e-14 -2.51187959321e-14
Check rotational invariance ...
System stress residue enduced by rigid-body rotations(eV/A)
   0.00000    0.00611    0.01347
   0.00611    0.00000    0.02417
   0.01347    0.02417    0.00000
Born-Huang rotational invariance condition (eV):    0.08197
Under the system symmetry
Number of first independent atoms:    2
Number of second independent atoms   30   20
Permutation symmetry reduces number of irreducible pairs from   50 to   40
Calculating transformation coefficients...
Number of independent fc2 components: 360
Traceback (most recent call last):
  File "/usr/local/bin/mdfc", line 324, in <module>
    is_rot_inv=settings.get_is_rotational_invariance())
  File "/usr/local/lib/python2.7/dist-packages/mdfc/force_constants.py", line 669, in set_fc2_irreducible_elements
    self.get_irreducible_fc2_components_with_spg()
  File "/usr/local/lib/python2.7/dist-packages/mdfc/force_constants.py", line 590, in get_irreducible_fc2_components_with_spg
    self._symmetry.get_symmetry_tolerance())
  File "/usr/local/lib/python2.7/dist-packages/mdfc/fc2.py", line 204, in get_fc2_spg_invariance
    CC, transform, independent = gaussian(np.array(CC))
  File "/usr/local/lib/python2.7/dist-packages/mdfc/fcmath.py", line 38, in gaussian
    import _mdfc
ImportError: /usr/local/lib/python2.7/dist-packages/mdfc/_mdfc.so: undefined symbol: LAPACKE_zheev

**Comment by Johnson-Wang** [comment]
In this case, you may need to install packages such as openblas, which contains lapacke module.

**Comment by MaxAbner** [comment]
I have tried to install `libopenblas-dev` `liblapacke-dev` `liblapack-dev`, but it didn't work

Still `ImportError: /usr/local/lib/python2.7/dist-packages/mdfc/_mdfc.so: undefined symbol: LAPACKE_zheev`
