### ISSUE TITLE
ImportError: cannot import name get_equivalent_smallest_vectors

### ISSUE THREAD

**Issue by llzz11** [Johnson-Wang/molatics#2]
Thank u for your reply .I link it to lapack ,and this question seems to have been solved.But when I run the line "nohup mdfc --readfc2=force_constants.hdf5 --dim="9 1 1" --ti --ri --precision=1e-6&",there is new matter:
Traceback (most recent call last):
  File "/usr/local/bin/mdfc", line 13, in <module> 
    from mdfc import MolecularDynamicsForceConstant as MDFC
  File "/usr/local/lib/python2.7/dist-packages/mdfc/__init__.py", line 7, in <module>
    from phonopy.harmonic.dynamical_matrix import get_equivalent_smallest_vectors
ImportError: cannot import name get_equivalent_smallest_vectors
Looking forward to your reply.

**Comment by Johnson-Wang** [comment]
It is due to the modifications I made on the source phonopy package. You can either find my version of phonopy in my github repository and build it (only phonopy is needed), or copy the needed function to your own phonopy version. 

Thanks
Johnson
