### ISSUE TITLE
The same question:ImportError: cannot import name get_equivalent_smallest_vectors

### ISSUE THREAD

**Issue by llzz11** [Johnson-Wang/molatics#3]
Thank u for your reply.But after I install your phonopy package with command"python2 setup.py install",it shows that I have installed it successfully.And I also install molatics with command “python2 setup.py install”again ,it also turns out being installed successfully.But again,when I run the code "nohup mdfc --readfc2=force_constants.hdf5 --dim="9 1 1" --ti --ri --precision=1e-6&",it shows the same mistake as before.

Traceback (most recent call last):
  File "/usr/local/bin/mdfc", line 13, in <module>
    from mdfc import MolecularDynamicsForceConstant as MDFC
  File "/usr/local/lib/python2.7/dist-packages/mdfc/__init__.py", line 7, in <module>
    from phonopy.harmonic.dynamical_matrix import get_equivalent_smallest_vectors
ImportError: cannot import name get_equivalent_smallest_vectors

Is there any details should I take care ?
Looking forward to your reply~~
Jason,
Sincerely thanks

**Comment by Johnson-Wang** [comment]
Weird... It should be found as you can locate the python module `phonopy.harmonic.dynamical_matrix.get_equivalent_smallest_vectors` yourself in `phonopy` module. Maybe you should check whether your PYTHONPATH includes the python installation directory?

**Comment by llzz11** [comment]
I put file"dynamical_matrix.py"into folder“mdfc”，and change all "phonopy.harmonic.dynamical_matrix."into"dynamical_matrix.py".This problem seems to be solved.But new failing occurs，when I run commands "mdfc" directly,it turns out:
 root@lz-VirtualBox:/home/lz/Desktop/molatics-mastermdfc# mdfc
        _
 __  __ ____  _____ ____
|  \/  |  _ \|  ___/ ___|
| |\/| | | | | |_ | |
| |  | | |_| |  _|| |___
|_|  |_|____/|_|   \____|

                         1.3

Traceback (most recent call last):
  File "/usr/local/bin/mdfc", line 297, in <module>
    is_hdf5=settings.get_is_hdf5())
  File "/usr/local/lib/python2.7/dist-packages/mdfc/__init__.py", line 73, in __init__
    self._set_supercell()
  File "/usr/local/lib/python2.7/dist-packages/mdfc/__init__.py", line 470, in _set_supercell
    self._symprec)
  File "build/bdist.linux-x86_64/egg/phonopy/structure/cells.py", line 44, in get_supercell
    def trim_cell(relative_axes, cell, symprec):
  File "build/bdist.linux-x86_64/egg/phonopy/structure/cells.py", line 130, in __init__
    line += "  %5.3f" % magmoms[i]
TypeError: long() argument must be a string or a number, not 'NoneType'

**Comment by Johnson-Wang** [comment]
Sorry for the late response. I would guess that the phonopy version you installed is different from mine. Actually I forked the phonopy project quite long ago and it might not be compatible any more. My suggestion is that you uninstall phonopy first and then install mine.
